# fly.toml file generated for carbonable-testnet-indexer on 2023-04-05T15:47:37+02:00

app = "carbonable-testnet-indexer"
kill_signal = "SIGINT"
kill_timeout = 5
primary_region = "cdg"

[processes]
# api = "./carbonable-api"
# indexer = "/srv/www/carbonable-indexer"

# [deploy]
#   release_command = "/srv/www/carbonable-migration"

[[services]]
  processes = ["api"]
  internal_port = 8080
  protocol = "tcp"
  script_checks = []

  [services.concurrency]
    hard_limit = 25
    soft_limit = 20
    type = "connections"

  [[services.ports]]
    force_https = true
    handlers = ["http"]
    port = 80

  [[services.ports]]
    handlers = ["tls", "http"]
    port = 443

  [[services.tcp_checks]]
    grace_period = "1s"
    interval = "15s"
    restart_limit = 0
    timeout = "2s"
