[package]
name = "carbonable-api"
version = "0.1.0"
edition = "2021"
publish = false

[dependencies]
carbonable-domain.workspace = true
bigdecimal.workspace = true
actix-web.workspace = true
apibara-sdk.workspace = true
starknet.workspace = true
async-trait.workspace = true
futures.workspace = true
futures-util.workspace = true
serde.workspace = true
serde_json.workspace = true
thiserror.workspace = true
tokio.workspace = true
tonic.workspace = true
uuid.workspace = true
ulid.workspace = true
env_logger.workspace = true
clap.workspace = true
tracing.workspace = true
ipfs-api-backend-hyper.workspace = true
reqwest.workspace = true
serde-aux.workspace = true
sea-query.workspace = true
deadpool-postgres.workspace = true
postgres-types.workspace = true
tokio-postgres.workspace = true
deadpool.workspace = true
sea-query-postgres.workspace = true
sea-orm-migration.workspace = true
